# Generated by Django 5.2.1 on 2025-06-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Nome do grupo de função', max_length=50, unique=True, verbose_name='Nome do Grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Função',
                'verbose_name_plural': 'Grupos de Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Nome da função policial', max_length=50, verbose_name='Nome da Função')),
                ('tipo', models.CharField(choices=[('O', 'Operacional'), ('G', 'Geral'), ('A', 'Administrativo')], default='G', max_length=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcoes', to='police.grupofuncao', verbose_name='Grupo de Função')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='police_func_nome_01ef97_idx'), models.Index(fields=['tipo'], name='police_func_tipo_e360fd_idx')],
            },
        ),
    ]
