# Generated by Django 5.2.1 on 2025-06-08 22:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_policial_fardamento_dadosfisicos_cnh_rg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('matricula_sad', models.CharField(blank=True, help_text='Matrícula no Sistema de Administração', max_length=20, null=True, verbose_name='Matrícula SAD')),
                ('documento_numero', models.CharField(help_text='Número/Descrição do documento que designou a função (ex: BOL PM Nº 001/2025)', max_length=100, verbose_name='Número do Documento')),
                ('documento_arquivo', models.FileField(blank=True, help_text='Arquivo digital do documento (PDF, DOC, etc)', null=True, upload_to='documentos/funcoes/%Y/%m/', verbose_name='Arquivo do Documento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='police.funcao', verbose_name='Função')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_funcoes', to='police.policial', verbose_name='Policial')),
            ],
            options={
                'verbose_name': 'Histórico de Função',
                'verbose_name_plural': 'Históricos de Funções',
                'ordering': ['-data_inicio', '-data_fim'],
                'indexes': [models.Index(fields=['data_inicio'], name='police_hist_data_in_133189_idx'), models.Index(fields=['data_fim'], name='police_hist_data_fi_12f6c0_idx'), models.Index(fields=['matricula_sad'], name='police_hist_matricu_93c3a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gt', models.F('data_inicio')), _connector='OR'), name='data_fim_maior_que_inicio')],
            },
        ),
    ]
