# Generated by Django 5.2.1 on 2025-06-09 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_historicofuncao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosfisicos',
            name='cor_cabelo',
        ),
        migrations.RemoveField(
            model_name='dadosfisicos',
            name='usa_oculos',
        ),
        migrations.AddField(
            model_name='dadosfisicos',
            name='cor_cabelos',
            field=models.CharField(choices=[('PR', 'Preto'), ('CA', 'Castanho'), ('LO', 'Loiro'), ('RU', 'Ruivo'), ('GR', 'Grisalho'), ('BR', 'Branco'), ('OU', 'Outro')], default=None, max_length=2, verbose_name='Cor do Cabelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosfisicos',
            name='tipo_cabelos',
            field=models.CharField(choices=[('LI', 'Liso'), ('ON', 'Ondulado'), ('CA', 'Cacheado'), ('CR', 'Crespo'), ('OU', 'Outro')], default=None, max_length=2, verbose_name='Tipo do Cabelo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policial',
            name='user',
            field=models.OneToOneField(default=1, help_text='Usuário do sistema associado ao policial', on_delete=django.db.models.deletion.PROTECT, related_name='policial', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosfisicos',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='dadosfisicos',
            name='cor_olhos',
            field=models.CharField(choices=[('CA', 'Castanho'), ('PR', 'Preto'), ('AZ', 'Azul'), ('VE', 'Verde'), ('AM', 'Amêndoa'), ('ME', 'Mel'), ('OU', 'Outro')], max_length=2, verbose_name='Cor dos Olhos'),
        ),
        migrations.AlterField(
            model_name='dadosfisicos',
            name='cor_pele',
            field=models.CharField(choices=[('BR', 'Branca'), ('PR', 'Preta'), ('PA', 'Parda'), ('AM', 'Amarela'), ('IN', 'Indígena'), ('OU', 'Outra')], max_length=2, verbose_name='Cor da Pele'),
        ),
        migrations.AlterField(
            model_name='dadosfisicos',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='dadosfisicos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
    ]
