# Generated by Django 5.2.1 on 2025-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_note_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
